### ISSUE TITLE
Error: "InAppBrowser" plugin is not implemented on ios / {"code":"UNIMPLEMENTED"} with @ionic/vue

### ISSUE THREAD

**Issue by tempire** [Cap-go/capacitor-inappbrowser#279]
I'm currently unable to get the plugin working. I'm at a loss as to what could be wrong.

@ionic/vue file:

```
<script setup>
import { InAppBrowser } from '@capgo/inappbrowser'
import { Capacitor } from "@capacitor/core"

...

try {
  console.log({isNative: Capacitor.isNativePlatform()})
  const thing = await InAppBrowser.open('http://apache.org')
}
catch (error) {
  console.log(error)
}
```

When run from `capacitor run ios --target 7E1FE4C3-A3C6-49E0-A358-FD4A91903697`
safari devtools console:
```
{isNative: true}
Error: "InAppBrowser" plugin is not implemented on ios
  CapacitorException — util.js:21
  createPluginMethod — runtime.js:69
  (anonymous function) — runtime.js:76
```

When run from xcode:
```
⚡️  [log] - {"isNative":true}
⚡️  [log] - {"code":"UNIMPLEMENTED"}
```

**Sync and build**
```
❯ npx cap sync ios
✔ Copying web assets from dist to ios/App/App/public in 123.02ms
✔ Creating capacitor.config.json in ios/App/App in 615.00μs
✔ copy ios in 165.55ms
✔ Updating iOS plugins in 1.72ms
✔ Updating iOS native dependencies with pod install in 1.85s
[info] Found 8 Capacitor plugins for ios:
       @aparajita/capacitor-biometric-auth@8.0.2
       @capacitor-mlkit/barcode-scanning@7.0.0-next.3
       @capacitor/app@7.0.0
       @capacitor/browser@7.0.0
       @capacitor/haptics@7.0.0
       @capacitor/keyboard@7.0.0
       @capacitor/status-bar@7.0.0
       @capgo/inappbrowser@7.2.9
✔ update ios in 1.90s
[info] Sync finished in 2.326s
```

```
> capacitor run ios --target 7E1FE4C3-A3C6-49E0-A358-FD4A91903697
[capacitor] ✔ Copying web assets from dist to ios/App/App/public in 71.35ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 433.71μs
[capacitor] [info] Inlining sourcemaps
[capacitor] ✔ copy ios in 127.16ms
[capacitor] ✔ Updating iOS plugins in 1.76ms
[capacitor] ✔ Updating iOS native dependencies with pod install in 2.68s
[capacitor] [info] Found 8 Capacitor plugins for ios:
[capacitor]        @aparajita/capacitor-biometric-auth@8.0.2
[capacitor]        @capacitor-mlkit/barcode-scanning@7.0.0-next.3
[capacitor]        @capacitor/app@7.0.0
[capacitor]        @capacitor/browser@7.0.0
[capacitor]        @capacitor/haptics@7.0.0
[capacitor]        @capacitor/keyboard@7.0.0
[capacitor]        @capacitor/status-bar@7.0.0
[capacitor]        @capgo/inappbrowser@7.2.9
[capacitor] ✔ update ios in 2.71s
[capacitor] ✔ Running xcodebuild in 10.93s
[capacitor] ✔ Deploying App.app to 7E1FE4C3-A3C6-49E0-A358-FD4A91903697 in 5.80s
```
```
❯ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 7.0.1
  @capacitor/core: 7.0.1
  @capacitor/android: 7.0.1
  @capacitor/ios: 7.0.1

Installed Dependencies:

  @capacitor/cli: 7.0.1
  @capacitor/core: 7.0.1
  @capacitor/android: 7.0.1
  @capacitor/ios: 7.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by tempire** [comment]
I tried a completely new project, but still the same result.

**Comment by tempire** [comment]
Addressed and fixed in https://github.com/Cap-go/capacitor-inappbrowser/issues/211

**Comment by mariomurrent-softwaresolutions** [comment]
Still getting the Errors "InAppBrowser plugin is not implemented on ios" when trying to use the Plugin on ios, capacitor 7
